"""Remove default from img_url

Revision ID: 54e34edb551b
Revises: 
Create Date: 2024-12-17 19:29:48.646167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e34edb551b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disorders', schema=None) as batch_op:
        batch_op.drop_constraint('disorders_name_key', type_='unique')
        batch_op.drop_constraint('unique_name', type_='unique')

    with op.batch_alter_table('disorders_signs', schema=None) as batch_op:
        batch_op.alter_column('sign_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disorders_signs', schema=None) as batch_op:
        batch_op.alter_column('sign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('disorders', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name', ['name'])
        batch_op.create_unique_constraint('disorders_name_key', ['name'])

    # ### end Alembic commands ###
